apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generic
  name: generic
  namespace: generic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generic
  template:
    metadata:
      labels:
        app: generic
    spec:
      containers:
        - name: generic
          image: ss-eefa/generic
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          lifecycle:
            preStop:
              exec:
                command: ["sh", "-c", "sleep 10"]
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: generic
  namespace: generic
  labels:
    app: generic
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: generic
  type: LoadBalancer

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: generic
  namespace: generic
#  annotations:
#    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - local.eefa.io
      secretName: local.eefa.io-ingress-tls
  rules:
    - host: local.eefa.io
      http:
        paths:
          - path: /generic(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: generic
                port:
                  number: 8080